---
- name: Install node and npm
  become: yes
  hosts: node-app
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes upgrade=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Deploying nodejs application
  become: yes
  hosts: node-app
  tasks:
    - name: unpack nodejs tar file
      unarchive:
        src: /home/ubuntu/codes/docker_web_app-1.0.0.tgz
        dest: /root/

