---
- name: Install node and npm
  become: yes
  hosts: node-app
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes upgrade=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Create new linux user for node app
  become: yes
  hosts: node-app
  tasks:
    - name: create linux user
      user:
        name: sonia
        comment: Sonia Admin
        groups: admin,sudo
        append: yes
- name: Deploying nodejs application
  hosts: node-app
  become: yes
  become_user: sonia
  tasks:
    - name: unpack nodejs tar file
      unarchive:
        src: /home/ubuntu/codes/docker_web_app-1.0.0.tgz
        dest: /home/sonia
    - name: Install node dependencies
      npm:
        path: /home/sonia/package/
    - name: Start the application
      command:
        chdir: /home/sonia/package/
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

