---
- name: Install node and npm
  become: yes
  hosts: node-app
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes upgrade=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Create new linux user for node app
  become: yes
  vars:
    - name: john
  hosts: node-app
  tasks:
    - name: create linux user
      user:
        name: "{{name}}"
        comment: "{{name}} Admin"
        group: admin
- name: Deploying nodejs application
  hosts: node-app
  become: true
  become_user: john
  vars:
    - location: /home/ubuntu/codes
    - version: 1.0.0
    - destination: /home/john
  tasks:
    - name: unpack nodejs tar file
      unarchive:
        src: "{{location}}/docker_web_app-{{version}}.tgz"
        dest: "{{destination}}"
    - name: Install node dependencies
      npm:
        path: "{{destination}}/package/"
    - name: Start the application
      command:
        chdir: "{{destination}}/package/"
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

